### ISSUE TITLE
Question about generated ply by pretrain model VS ply model on project page

### ISSUE THREAD

**Issue by Cli98** [zju3dv/manhattan_sdf#12]
Hi @ghy0324 

Thank you again for this wonderful project! 

I have a question regarding your presented model. In your webpage , I do see reconstruction with high texture quality. 
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/19630616/173398505-7683fe27-b7cb-4bf9-ae7d-61993df0fcde.png">

However from the evaluation data you provided (gt.obj) and inference result(I refer to ply model), I have not observed similar quality. Here is a capture.

<img width="707" alt="image" src="https://user-images.githubusercontent.com/19630616/173399842-c35d085e-342c-4366-83ae-63138e7c7d68.png">

****Can you explain why?**** 

The visualization comes from meshlab. The file downloaded from eval zip file you provided https://zjueducn-my.sharepoint.com/personal/guohaoyu_zju_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fguohaoyu%5Fzju%5Fedu%5Fcn%2FDocuments%2Fmanhattan%5Fsdf%2Fdata%2Fmanhattan%5Fsdf%5Fscannet%5Fdata&ga=1

Another question is, how to achieve high quality texture as presented in your project webpage? I have not found specific detail in your paper. And I will be appreciate if you can point out explicitly which section you discussed this.

Thank you,

**Comment by jinmaodaomaye2021** [comment]
I have the same issue in model training.
Created a new thread https://github.com/zju3dv/manhattan_sdf/issues/13#issue-1269778098

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!

The geometry of the mesh in webpage is same as the inference result (you can turn off the texture and visualize geometry only on webpage). The only reason making the visualization difference is that we use texture mapping for the mesh in webpage, while the inference result is just of vertice colors, which are obtained by simple RGBD fusion. 

Since our work focus on geometry reconstruction only, we are not going to provide detailed instruction on texture mapping. You can use off-the-shelf texture mapping tools such as [mvs-texturing](https://github.com/nmoehrle/mvs-texturing) after reconstruction to obtain similar visualization results.

**Comment by xiehousen** [comment]
hello, have you successfully generated the point cloud of texture map like the OBJ in the project website? Can you share how to get this result?

Thanks in advance.
