### ISSUE TITLE
The script to generate groundtruth mesh

### ISSUE THREAD

**Issue by jcliu0428** [zju3dv/manhattan_sdf#37]
Hi authors,

Thank you for sharing your great work! I notice that you are using the mesh generated by TSDF-fusion by Open3d instead of the original mesh provided by ScanNet to evaluate your results. I am expecting to generate the groundtruth mesh with you in the same manner for a fair comparison with our algorithm. So it will be great if you can share the script!

Thanks!

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!
You can use [this script](https://github.com/zju3dv/manhattan_sdf/blob/604944fd37cd8eb9045f4eb8ec4f994269981af4/lib/utils/mesh_utils.py#L50-L78) with slight modifications: Use the ground truth depth maps instead of rendered depth, and do not multiply `cfg.test_dataset.scale` if you use the original (instead of normalized) depth maps and poses provided by ScanNet.
Feel free to contact me if you have any further questions!

**Comment by jcliu0428** [comment]
Thanks! I tried the script and it works well!

**Comment by 00Haocheng** [comment]
I found that manhattan-sdf use only 1/10 figures to reconstruction. So when generate gt mesh use real depth map in scannet, do you use all the figure or just the same 1/10 figures
