### ISSUE TITLE
Invalid values generated by sdf_net

### ISSUE THREAD

**Issue by jackie840129** [zju3dv/manhattan_sdf#43]
Hi @ghy0324 @pengsida ,

Thanks for your great work, I've tried it on my custom scene and it works successfully!
However, when I try to reconstruct on a more difficult scene such like the entire home with one-time recording by my cell phone (sush as the floorplan below), the model will fail on the mesh extraction part.

In `utils/mesh_utils.py`, the function `extract_mesh()` will first generate the sdf with volume (NxNxN). However, my model predict all negative values in the sdf, which makes the following `marching_cubes()` fails.

Can you kindly give me some opinions that what is the root cause of this scenario?. Is it the model capacity problem because my scene is too large (~10m x ~10m) to remember? Or other problems owing to the input pose or input depth. I normalized the pose to a unit sphere and if I trained on a small scene such as the living room, the model works perfectly.

Thanks!!

![room layout](https://user-images.githubusercontent.com/16732981/217765302-100f5210-7023-48a4-bab1-642bff835dcc.png)

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!
We didn’t try our method on such kind of scenes. I think it’s not because of the scale of scene. When scene is too large, the reconstruction results maybe rough because of the limitation of model capacity, but it should not fail.
One possible reason is the structure of the scene. When there are multiple rooms, the structure (or topology) of reconstruction target is complex, the model maybe hard to learn it from sphere initialization.

**Comment by jackie840129** [comment]
Hi Thanks for your opinion. After I tried deep-learning based depth estimation model (refer from MonoSDF), I can reconstruct it!  I think Colmap cannot obtain correct depth for this sophisticated scene.
