### ISSUE TITLE
Problem on data preparation

### ISSUE THREAD

**Issue by rainfall1998** [zju3dv/manhattan_sdf#5]
Hi, thanks for your wonderful work!
I woud like to train on the new recorded sequences. so I wonder when the 'Data preparation' will be published?
Looking forward to your early reply.

**Comment by ghy0324** [comment]
Hi! Thanks for your interest!

Since the procedure of data preparation is a little complicated, we still need some time to release the final document. We provide the draft here, hope it is helpful for you. Welcome for your feedback, which can be helpful for us to improve the document!

Before preparing your own data, you should checkout the [dataset module](../tree/main/lib/datasets/scannet.py) carefully.

Overall, you need to place your data with the following structure and create a corresponding config file.
```
manhattan_sdf
├───data
|   ├───$scene_name
|   |   ├───intrinsic.txt
|   |   ├───images
|   |   |   ├───0.png
|   |   |   ├───1.png
|   |   |   └───...
|   |   ├───pose
|   |   |   ├───0.txt
|   |   |   ├───1.txt
|   |   |   └───...
|   |   ├───depth_colmap
|   |   |   ├───0.npy
|   |   |   ├───1.npy
|   |   |   └───...
|   |   └───semantic_deeplab
|   |       ├───0.png
|   |       ├───1.png
|   |       └───...
|   └───...
├───configs
|   ├───$scene_name.yaml
|   └───...
└───...
```
## Images
You should place RGB images in `data/$scene_name/images` folder, note that the filenames can be arbitrary but you need to make sure that they are consistent with files in other folders under `data/$scene_name`.

## Intrinsic parameters
Save the `4x4` intrinsic matrix in `data/$scene_name/intrinsic.txt`.

## Camera poses
You can solve camera poses with COLMAP or other tools you like. Then you need to normalize the camera poses and modify some configs to ensure that:
- The scene is inside [bounding radius](../tree/main/configs/scannet/0050.yaml#L14), note that bounding radius should be lower than <img src="https://render.githubusercontent.com/render/math?math=\pi"> so that positional encoding can work well.
- The center of the scene is near the origin and the [geometric initialization radius](../tree/main/configs/scannet/0050.yaml#L17) is appropriate (surface of initialized sphere and target geometry should not be too far).
- Make sure that the sampling range ([near](../tree/main/configs/scannet/0050.yaml#L41), [far](../tree/main/configs/scannet/0050.yaml#L42)) can cover the whole scene.

Save the normalized poses as `4x4` matrices in `txt` format under `data/$scene_name/pose` folder. Remember to save the scale and offset you used to normalize [here](../tree/main/configs/scannet/0050.yaml#L50) so that you can transform to original coordinate if you want to extract mesh and compare with ground truth mesh.

## COLMAP depth maps
You need to run sparse and dense reconstruction of COLMAP first. Please refer to this [instruction](https://colmap.github.io/faq.html#reconstruct-sparse-dense-model-from-known-camera-poses) if you want to use known camera poses.

After dense reconstruction, you can obtain depth prediction for each view. However, the depth predictions can be noisy, so we recommend you to run fusion first to filter out most noises. Since original COLMAP does not have fusion mask for each view, you need to compile and run [this customized version](https://github.com/B1ueber2y/colmap/tree/c84269d693246d8294307cc32f851813f18b6a2d), which is used in [NerfingMVS](https://github.com/weiyithu/NerfingMVS).

## Semantic predictions
You need to run 2D semantic segmentations to generate semantic predictions from images. We will upload our trained model and inference code soon.

**Comment by rainfall1998** [comment]
Thanks for your reply.
It is the first time for me to use the scannet dataset. However, I find little information about calibration on the github of scannet.  Could you share some experience about the image and depth calibration of the scannet dataset? Do I need to undistort the rgb and depth, or just extract them from .sens ?
 And the scaling interpolation method you use is nearest neighbor or Bilinear? 
Thank you very much!

**Comment by ghy0324** [comment]
> Thanks for your reply. It is the first time for me to use the scannet dataset. However, I find little information about calibration on the github of scannet. Could you share some experience about the image and depth calibration of the scannet dataset? Do I need to undistort the rgb and depth, or just extract them from .sens ? And the scaling interpolation method you use is nearest neighbor or Bilinear? Thank you very much!

We just extract them from `.sens` file using the [official code](https://github.com/ScanNet/ScanNet/tree/master/SensReader/python).
We use bilinear interpolation to rescale RGB images.

**Comment by rainfall1998** [comment]
Thank you very much!
