### ISSUE TITLE
Quantify the results

### ISSUE THREAD

**Issue by 05063112lcs** [zju3dv/manhattan_sdf#60]
Hello, thank you very much for your excellent work, I would like to know where to get some quantitative data indicators after running your project?

**Comment by ghy0324** [comment]
Hi! Thanks for your interest! When we conducted experiments on ScanNet, since there was sensor depth data in the dataset, we were able to obtain ground truth geometry through RGB-D fusion, which allowed us to perform quantitative evaluation of the reconstruction results from our RGB-based method. For data without ground truth depth, it may not be possible to quantitatively evaluate the geometric reconstruction results.
