### ISSUE TITLE
Why did you comment this line? 

### ISSUE THREAD

**Issue by DecaYale** [zju3dv/manhattan_sdf#63]
Hi, I found line 156 in run.py generated wrong masks on my dataset while the depth maps are reasonable. Did you have similar issues before? I noticed that you have commented this line in your script. Is the masking procedure adopted in your paper? Thank you!

https://github.com/zju3dv/manhattan_sdf/blob/c5e1503afdec8a50534d1022fecf9245dc9e99b5/docs/run_colmap/run.py#L156

```
for name, mask in tqdm(zip(names, masks)):
        depth_bin_path = f'{target}/dense/stereo/depth_maps/{name}.geometric.bin'
        if not os.path.exists(depth_bin_path):
            continue
        depth_fname = depth_bin_path
        depth = read_array(depth_fname)
        # depth[mask == 0] = 0
        np.save(f'{target}/depth_colmap/{name[:-4]}.npy', depth)
```

**Comment by ghy0324** [comment]
Hi! Thank you for your interest in our work!

Our original goal was to generate masks to retain only the depth values of pixels that are kept during the fusion process. However, we later discovered that the order of the masks are disrupted. As a result, we commented this line. In fact, whether this line is commented or not has little impact on the results, as the current masks behave like randomly masking due to the wrong ordering. If the correct order could be restored, the final results might potentially be improved using the masks.

Welcome for further discussion.
